# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b79e612a5917cb8624c87c64a4a83b32a438491f2485c96dd38602bd5f4a1177387fd6dfe444884a1206ba5a5806e62dba02bef8f926db2a94ad1aad8130c5b

test:
  secret_key_base: 659cdbc31bdd246176ad88f45bda94a143ba8d6001305f2e1d5f59ad05217c89f9cd58e6cbc735e102caa0a445ff04b0f774061d8e74eac6203c964307ab6705

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
